### ISSUE TITLE
cant run the app

### ISSUE THREAD

**Issue by bgkillas** [chxrlt/lyrebird#5]
can we have a more verbose requirements list like is this python 2 or 3? what modules are needed?

**Comment by harrego** [comment]
Hey, what have you tried? Did you run `install.sh`?

`toml` is the only module needed in Python and Python 3, `sox` and Python GTK (should work out of the box on Linux) are required system level.

**Comment by nesper8** [comment]
Same unable to run lyrebird

Installing required pip3 modules
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: toml in /usr/lib/python3.8/site-packages (0.10.1)
Installed Lyrebird to /usr/local/bin/lyrebird/
Installed Lyrebird.desktop to /usr/local/share/applications/

This is the terminal output after installing

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import lyrebird.mainwindow as mainwindow
ModuleNotFoundError: No module named 'lyrebird.mainwindow'

this error appears when ran with python3 app.py from /usr/local/bin/lyrebird

**Comment by bgkillas** [comment]
now it works ig first update was borked
